### ISSUE TITLE
igprof broken for 12_0_0_pre4 due to py2/3 in cmssw

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#17]
Currently, the jenkins jobs for 12_0_0_pre4 profiling had some issues with igprof which I'm debugging. II will update this post when 12_0_0_pre4 profiling is ready for further analysis.

**Comment by jpata** [comment]
```bash
cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM --conditions auto:phase2_realistic_T15 --datatier AODSIM -n 10 --eventcontent AODSIM --geometry Extended2026D49 --era Phase2C9 --pileup AVE_200_BX_25ns --pileup_input das:/RelValMinBias_14TeV/CMSSW_11_3_0_pre4-113X_mcRun4_realistic_v4_2026D49noPU_rsb-v1/GEN-SIM "-n 10" --filein  file:step2.root  --fileout file:step3.root   --suffix "-j step3_JobReport.xml" --customise Validation/Performance/IgProfInfo.customise --no_exec --python_filename step3_igprof.py &> step3_igprof_conf.txt
```
fails with

```
customising the process with customise from Validation/Performance/IgProfInfo
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/bin/slc7_amd64_gcc900/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/bin/slc7_amd64_gcc900/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/python/Configuration/Applications/ConfigBuilder.py", line 2303, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/python/Configuration/Applications/ConfigBuilder.py", line 913, in addCustomise
    self.process=getattr(package,fcn)(self.process)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/python/Validation/Performance/IgProfInfo.py", line 7, in customise
    reportEventInterval         = cms.untracked.int32( ((process.maxEvents.input.value()-1)/2) ), # dump in the middle of the run
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/python/FWCore/ParameterSet/Types.py", line 31, in __call__
    param = globals()[self.name](*value,**params)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/python/FWCore/ParameterSet/Mixins.py", line 96, in __init__
    raise ValueError(str(value)+" is not a valid "+str(type(self)))
ValueError: 4.5 is not a valid <class 'FWCore.ParameterSet.Types.int32'>

```

**Comment by slava77** [comment]
@jpata 
did you find a solution yet?
I have a fix in https://github.com/cms-sw/cmssw/pull/34517

**Comment by jpata** [comment]
Thanks for tracing it down! I'll give another try on jenkins with https://github.com/jpata/cms-bot/commit/5b8f31455cf75f3c6f9b9a47ae8a369e6e1ba011.

**Comment by jpata** [comment]
Seems like it didn't work. I'm inclined to drop it and wait for pre5 with the fix.

**Comment by jpata** [comment]
@xoqhdgh1002 could you take another look at step4 for pre4, and add TimeDiff, CompareOutProd for step4 on the web page with a PR? Thanks.

Let's skip igprof for pre4, I removed the links in #19 to avoid confusion.

**Comment by xoqhdgh1002** [comment]
I uploaded TimeDiff, CompareOutProd for step4 on the web page with a PR and fixed preview values!
Please check and comments. Thanks.

**Comment by jpata** [comment]
Thank you, pre4 is now updated!
